In [15]:
import numpy as np

#### task1 

In [5]:
a = np.array([[1, 6],[2, 8], [3, 11], [3, 10], [1, 7]])

In [6]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [7]:
mean_a = a.mean(axis=0)

In [32]:
mean_a

array([2. , 8.4])

#### task2

In [9]:
a_centered = a - mean_a

In [33]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

#### task3

In [28]:
column1 = np.array(a_centered.T[0])

In [29]:
print(column1)

[-1.  0.  1.  1. -1.]


In [30]:
column2 = np.array(a_centered.T[1])
print(column2)

[-2.4 -0.4  2.6  1.6 -1.4]


In [31]:
a_centered_sp = column1.dot(column2)
print(a_centered_sp)

8.0


In [34]:
cov1 = a_centered_sp/(column1.size - 1)

In [35]:
print(cov1)

2.0


#### task4

In [36]:
cov2 = np.cov(a.T)[0, 1]

In [37]:
print(cov2)

2.0
